[build]
  base = "."
  command = "node build-script.js"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
