[build]
  base = "."
  command = "npm install && npx vite build --outDir dist/public --base ./"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
