[build]
  base = "client"
  command = "npm install --prefix .. && npm run build --prefix .."
  publish = "../dist/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
