[build]
  base = "."
  command = "npm install && cd client && npx vite build --outDir ../dist/public --base ./"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
