[build]
  base = "."
  command = "npm install && npx vite build --config vite-netlify.config.ts"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200